project_id = "zxijdvdzbtrzgwwgdmbo"

[global.env]
STRIPE_SECRET_KEY = "stripe_secret_key"
STRIPE_WEBHOOK_SECRET = "stripe_webhook_secret"

[[functions]]
name = "test-stripe-connection"
verify_jwt = false