// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxijdvdzbtrzgwwgdmbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4aWpkdmR6YnRyemd3d2dkbWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMjgzMTgsImV4cCI6MjA1MDkwNDMxOH0.qePcsP48Nz-v0uORwPb7ltXKgBjeVecdg9vnYIB_4aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);