// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpvondndshfylzowgmyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwdm9uZG5kc2hmeWx6b3dnbXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNjM5MzMsImV4cCI6MjA1MDkzOTkzM30.ZTH-YvRgSI7LL9g-9SmN73gflKS5pKI9WEGs87XiwNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);